name: bargaining
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.20.0
  - pip        # (1) install pip itself
  - pip:
      - otree>=5.0.0   # (2) then use pip to install otree
      - requests
